# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.8"
  apt_packages:
    - graphviz
  commands:
    # Download and extract CMake
    - curl -L https://github.com/Kitware/CMake/releases/download/v3.27.0/cmake-3.27.0-linux-x86_64.tar.gz -o cmake.tar.gz
    - tar -xzf cmake.tar.gz
    # Create a local bin directory and move cmake there
    - mkdir -p ~/bin
    - mv cmake-3.27.0-linux-x86_64/bin/cmake ~/bin/cmake
    # Add the local bin directory to PATH
    - export PATH="$HOME/bin:$PATH"
    # Verify cmake installation
    - cmake --version
    # Build and install the project
    - python3 setup.py build
    - python3 setup.py install
  
# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Declare the Python requirements required to build your documentation
python:
  install:
    - requirements: docs/requirements.txt

