[project]
name = "test_ssapy_denvirhiggins"
version = "0.7.0"
authors = [
    { name="Denvir Higgins", email="denvir.j.higgins@gmail.com" },
]
description = "A small example package"
readme = "README.rst"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = { file = "LICENSE" }

[project.urls]
Homepage = "https://github.com/LLNL/SSAPy"
Issues = "https://github.com/LLNL/SSAPy/issues"

[build-system]
requires = ["setuptools", "wheel", "scikit-build-core"]
build-backend = "setuptools.build_meta"

[tool.scikit-build]
build-dir = "build"
wheel.packages = ["ssapy"]

[tool.setuptools.package-data]
exclude = ["ssapy/data/**"]