[project]
name = "test_ssapy_denvirhiggins"
version = "0.7.4"
authors = [
    { name="Denvir Higgins", email="denvir.j.higgins@gmail.com" },
]
description = "A small example package"
readme = "README.rst"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = { file = "LICENSE" }

[project.urls]
Homepage = "https://github.com/LLNL/SSAPy"
Issues = "https://github.com/LLNL/SSAPy/issues"

[build-system]
requires = ["setuptools>=42", "wheel", "scikit-build", "pybind11"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["ssapy"]
include-package-data = true

[tool.setuptools.package-data]
ssapy = ["*.cpp", "*.h"]

[tool.setuptools.exclude-package-data]
ssapy = ["data/*"]